# Generated by Django 4.2.4 on 2023-08-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='desProdut',
            field=models.CharField(max_length=100, verbose_name='Descricão'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preProdut',
            field=models.FloatField(verbose_name='Preço'),
        ),
    ]
