# Generated by Django 4.2.4 on 2023-08-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srb', '0002_alter_produtos_desprodut_alter_produtos_preprodut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='preProdut',
            field=models.FloatField(verbose_name='Preco'),
        ),
    ]
