# Generated by Django 4.2.4 on 2023-08-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srb', '0003_alter_produtos_preprodut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='preProdut',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preco'),
        ),
    ]
